// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/depositrequestresp.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from src/depositrequestresp.proto</summary>
public static partial class DepositrequestrespReflection {

  #region Descriptor
  /// <summary>File descriptor for src/depositrequestresp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DepositrequestrespReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChxzcmMvZGVwb3NpdHJlcXVlc3RyZXNwLnByb3RvIqcBChJEZXBvc2l0UmVx",
          "dWVzdFJlc3ASDAoEY29kZRgBIAEoCRIYChBwYXltZW50Vm91Y2hlck5vGAIg",
          "ASgJEhMKC3RyYWRlU3RhdHVzGAMgASgFEg4KBmV4dFVybBgEIAEoCRIMCgRl",
          "eHQxGAUgASgJEgwKBGV4dDIYBiABKAkSDAoEZXh0MxgHIAEoCRIMCgRleHQ0",
          "GAggASgJEgwKBGV4dDUYCSABKAlCLgosY29tLmxhd3NvZm5hdHVyZS5hcGln",
          "YXRld2F5LmRvbWFpbi5odHRwLnJlc3BiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::DepositRequestResp), global::DepositRequestResp.Parser, new[]{ "Code", "PaymentVoucherNo", "TradeStatus", "ExtUrl", "Ext1", "Ext2", "Ext3", "Ext4", "Ext5" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class DepositRequestResp : pb::IMessage<DepositRequestResp> {
  private static readonly pb::MessageParser<DepositRequestResp> _parser = new pb::MessageParser<DepositRequestResp>(() => new DepositRequestResp());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<DepositRequestResp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DepositrequestrespReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DepositRequestResp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DepositRequestResp(DepositRequestResp other) : this() {
    code_ = other.code_;
    paymentVoucherNo_ = other.paymentVoucherNo_;
    tradeStatus_ = other.tradeStatus_;
    extUrl_ = other.extUrl_;
    ext1_ = other.ext1_;
    ext2_ = other.ext2_;
    ext3_ = other.ext3_;
    ext4_ = other.ext4_;
    ext5_ = other.ext5_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DepositRequestResp Clone() {
    return new DepositRequestResp(this);
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 1;
  private string code_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Code {
    get { return code_; }
    set {
      code_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "paymentVoucherNo" field.</summary>
  public const int PaymentVoucherNoFieldNumber = 2;
  private string paymentVoucherNo_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string PaymentVoucherNo {
    get { return paymentVoucherNo_; }
    set {
      paymentVoucherNo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "tradeStatus" field.</summary>
  public const int TradeStatusFieldNumber = 3;
  private int tradeStatus_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int TradeStatus {
    get { return tradeStatus_; }
    set {
      tradeStatus_ = value;
    }
  }

  /// <summary>Field number for the "extUrl" field.</summary>
  public const int ExtUrlFieldNumber = 4;
  private string extUrl_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ExtUrl {
    get { return extUrl_; }
    set {
      extUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext1" field.</summary>
  public const int Ext1FieldNumber = 5;
  private string ext1_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext1 {
    get { return ext1_; }
    set {
      ext1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext2" field.</summary>
  public const int Ext2FieldNumber = 6;
  private string ext2_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext2 {
    get { return ext2_; }
    set {
      ext2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext3" field.</summary>
  public const int Ext3FieldNumber = 7;
  private string ext3_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext3 {
    get { return ext3_; }
    set {
      ext3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext4" field.</summary>
  public const int Ext4FieldNumber = 8;
  private string ext4_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext4 {
    get { return ext4_; }
    set {
      ext4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ext5" field.</summary>
  public const int Ext5FieldNumber = 9;
  private string ext5_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ext5 {
    get { return ext5_; }
    set {
      ext5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as DepositRequestResp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(DepositRequestResp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Code != other.Code) return false;
    if (PaymentVoucherNo != other.PaymentVoucherNo) return false;
    if (TradeStatus != other.TradeStatus) return false;
    if (ExtUrl != other.ExtUrl) return false;
    if (Ext1 != other.Ext1) return false;
    if (Ext2 != other.Ext2) return false;
    if (Ext3 != other.Ext3) return false;
    if (Ext4 != other.Ext4) return false;
    if (Ext5 != other.Ext5) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Code.Length != 0) hash ^= Code.GetHashCode();
    if (PaymentVoucherNo.Length != 0) hash ^= PaymentVoucherNo.GetHashCode();
    if (TradeStatus != 0) hash ^= TradeStatus.GetHashCode();
    if (ExtUrl.Length != 0) hash ^= ExtUrl.GetHashCode();
    if (Ext1.Length != 0) hash ^= Ext1.GetHashCode();
    if (Ext2.Length != 0) hash ^= Ext2.GetHashCode();
    if (Ext3.Length != 0) hash ^= Ext3.GetHashCode();
    if (Ext4.Length != 0) hash ^= Ext4.GetHashCode();
    if (Ext5.Length != 0) hash ^= Ext5.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Code.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Code);
    }
    if (PaymentVoucherNo.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(PaymentVoucherNo);
    }
    if (TradeStatus != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TradeStatus);
    }
    if (ExtUrl.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ExtUrl);
    }
    if (Ext1.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Ext1);
    }
    if (Ext2.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Ext2);
    }
    if (Ext3.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Ext3);
    }
    if (Ext4.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Ext4);
    }
    if (Ext5.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Ext5);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Code.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Code);
    }
    if (PaymentVoucherNo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PaymentVoucherNo);
    }
    if (TradeStatus != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TradeStatus);
    }
    if (ExtUrl.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ExtUrl);
    }
    if (Ext1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext1);
    }
    if (Ext2.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext2);
    }
    if (Ext3.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext3);
    }
    if (Ext4.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext4);
    }
    if (Ext5.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ext5);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(DepositRequestResp other) {
    if (other == null) {
      return;
    }
    if (other.Code.Length != 0) {
      Code = other.Code;
    }
    if (other.PaymentVoucherNo.Length != 0) {
      PaymentVoucherNo = other.PaymentVoucherNo;
    }
    if (other.TradeStatus != 0) {
      TradeStatus = other.TradeStatus;
    }
    if (other.ExtUrl.Length != 0) {
      ExtUrl = other.ExtUrl;
    }
    if (other.Ext1.Length != 0) {
      Ext1 = other.Ext1;
    }
    if (other.Ext2.Length != 0) {
      Ext2 = other.Ext2;
    }
    if (other.Ext3.Length != 0) {
      Ext3 = other.Ext3;
    }
    if (other.Ext4.Length != 0) {
      Ext4 = other.Ext4;
    }
    if (other.Ext5.Length != 0) {
      Ext5 = other.Ext5;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Code = input.ReadString();
          break;
        }
        case 18: {
          PaymentVoucherNo = input.ReadString();
          break;
        }
        case 24: {
          TradeStatus = input.ReadInt32();
          break;
        }
        case 34: {
          ExtUrl = input.ReadString();
          break;
        }
        case 42: {
          Ext1 = input.ReadString();
          break;
        }
        case 50: {
          Ext2 = input.ReadString();
          break;
        }
        case 58: {
          Ext3 = input.ReadString();
          break;
        }
        case 66: {
          Ext4 = input.ReadString();
          break;
        }
        case 74: {
          Ext5 = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
