// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/socketresponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from src/socketresponse.proto</summary>
public static partial class SocketresponseReflection {

  #region Descriptor
  /// <summary>File descriptor for src/socketresponse.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SocketresponseReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhzcmMvc29ja2V0cmVzcG9uc2UucHJvdG8ipQIKDlNvY2tldFJlc3BvbnNl",
          "EgoKAnAxGAEgASgJEgoKAnAyGAIgASgJEgoKAnAzGAMgASgJEgoKAnA0GAQg",
          "ASgJEgoKAnA1GAUgASgJEgoKAnA2GAYgASgJEgoKAnA3GAcgASgJEgoKAnA4",
          "GAggASgJEgoKAnA5GAkgASgJEgsKA3AxMBgKIAEoCRILCgNwMTEYCyABKAkS",
          "CwoDcDEyGAwgASgJEgsKA3AxMxgNIAEoCRILCgNwMTQYDiABKAkSCwoDcDE1",
          "GA8gASgJEgsKA3AxNhgQIAEoCRILCgNwMTcYESABKAkSCwoDcDE4GBIgASgJ",
          "EgsKA3AxORgTIAEoCRILCgNwMjAYFCABKAkSCwoDcDIxGBUgASgJEgsKA3Ay",
          "MhgWIAEoCUInCiVjb20uanhqeGdvLmdhbWVnYXRld2F5LmRvbWFpbi53cy5y",
          "ZXNwYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SocketResponse), global::SocketResponse.Parser, new[]{ "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10", "P11", "P12", "P13", "P14", "P15", "P16", "P17", "P18", "P19", "P20", "P21", "P22" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SocketResponse : pb::IMessage<SocketResponse> {
  private static readonly pb::MessageParser<SocketResponse> _parser = new pb::MessageParser<SocketResponse>(() => new SocketResponse());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SocketResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SocketresponseReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SocketResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SocketResponse(SocketResponse other) : this() {
    p1_ = other.p1_;
    p2_ = other.p2_;
    p3_ = other.p3_;
    p4_ = other.p4_;
    p5_ = other.p5_;
    p6_ = other.p6_;
    p7_ = other.p7_;
    p8_ = other.p8_;
    p9_ = other.p9_;
    p10_ = other.p10_;
    p11_ = other.p11_;
    p12_ = other.p12_;
    p13_ = other.p13_;
    p14_ = other.p14_;
    p15_ = other.p15_;
    p16_ = other.p16_;
    p17_ = other.p17_;
    p18_ = other.p18_;
    p19_ = other.p19_;
    p20_ = other.p20_;
    p21_ = other.p21_;
    p22_ = other.p22_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SocketResponse Clone() {
    return new SocketResponse(this);
  }

  /// <summary>Field number for the "p1" field.</summary>
  public const int P1FieldNumber = 1;
  private string p1_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P1 {
    get { return p1_; }
    set {
      p1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p2" field.</summary>
  public const int P2FieldNumber = 2;
  private string p2_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P2 {
    get { return p2_; }
    set {
      p2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p3" field.</summary>
  public const int P3FieldNumber = 3;
  private string p3_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P3 {
    get { return p3_; }
    set {
      p3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p4" field.</summary>
  public const int P4FieldNumber = 4;
  private string p4_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P4 {
    get { return p4_; }
    set {
      p4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p5" field.</summary>
  public const int P5FieldNumber = 5;
  private string p5_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P5 {
    get { return p5_; }
    set {
      p5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p6" field.</summary>
  public const int P6FieldNumber = 6;
  private string p6_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P6 {
    get { return p6_; }
    set {
      p6_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p7" field.</summary>
  public const int P7FieldNumber = 7;
  private string p7_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P7 {
    get { return p7_; }
    set {
      p7_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p8" field.</summary>
  public const int P8FieldNumber = 8;
  private string p8_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P8 {
    get { return p8_; }
    set {
      p8_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p9" field.</summary>
  public const int P9FieldNumber = 9;
  private string p9_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P9 {
    get { return p9_; }
    set {
      p9_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p10" field.</summary>
  public const int P10FieldNumber = 10;
  private string p10_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P10 {
    get { return p10_; }
    set {
      p10_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p11" field.</summary>
  public const int P11FieldNumber = 11;
  private string p11_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P11 {
    get { return p11_; }
    set {
      p11_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p12" field.</summary>
  public const int P12FieldNumber = 12;
  private string p12_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P12 {
    get { return p12_; }
    set {
      p12_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p13" field.</summary>
  public const int P13FieldNumber = 13;
  private string p13_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P13 {
    get { return p13_; }
    set {
      p13_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p14" field.</summary>
  public const int P14FieldNumber = 14;
  private string p14_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P14 {
    get { return p14_; }
    set {
      p14_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p15" field.</summary>
  public const int P15FieldNumber = 15;
  private string p15_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P15 {
    get { return p15_; }
    set {
      p15_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p16" field.</summary>
  public const int P16FieldNumber = 16;
  private string p16_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P16 {
    get { return p16_; }
    set {
      p16_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p17" field.</summary>
  public const int P17FieldNumber = 17;
  private string p17_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P17 {
    get { return p17_; }
    set {
      p17_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p18" field.</summary>
  public const int P18FieldNumber = 18;
  private string p18_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P18 {
    get { return p18_; }
    set {
      p18_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p19" field.</summary>
  public const int P19FieldNumber = 19;
  private string p19_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P19 {
    get { return p19_; }
    set {
      p19_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p20" field.</summary>
  public const int P20FieldNumber = 20;
  private string p20_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P20 {
    get { return p20_; }
    set {
      p20_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p21" field.</summary>
  public const int P21FieldNumber = 21;
  private string p21_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P21 {
    get { return p21_; }
    set {
      p21_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "p22" field.</summary>
  public const int P22FieldNumber = 22;
  private string p22_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string P22 {
    get { return p22_; }
    set {
      p22_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SocketResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SocketResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (P1 != other.P1) return false;
    if (P2 != other.P2) return false;
    if (P3 != other.P3) return false;
    if (P4 != other.P4) return false;
    if (P5 != other.P5) return false;
    if (P6 != other.P6) return false;
    if (P7 != other.P7) return false;
    if (P8 != other.P8) return false;
    if (P9 != other.P9) return false;
    if (P10 != other.P10) return false;
    if (P11 != other.P11) return false;
    if (P12 != other.P12) return false;
    if (P13 != other.P13) return false;
    if (P14 != other.P14) return false;
    if (P15 != other.P15) return false;
    if (P16 != other.P16) return false;
    if (P17 != other.P17) return false;
    if (P18 != other.P18) return false;
    if (P19 != other.P19) return false;
    if (P20 != other.P20) return false;
    if (P21 != other.P21) return false;
    if (P22 != other.P22) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (P1.Length != 0) hash ^= P1.GetHashCode();
    if (P2.Length != 0) hash ^= P2.GetHashCode();
    if (P3.Length != 0) hash ^= P3.GetHashCode();
    if (P4.Length != 0) hash ^= P4.GetHashCode();
    if (P5.Length != 0) hash ^= P5.GetHashCode();
    if (P6.Length != 0) hash ^= P6.GetHashCode();
    if (P7.Length != 0) hash ^= P7.GetHashCode();
    if (P8.Length != 0) hash ^= P8.GetHashCode();
    if (P9.Length != 0) hash ^= P9.GetHashCode();
    if (P10.Length != 0) hash ^= P10.GetHashCode();
    if (P11.Length != 0) hash ^= P11.GetHashCode();
    if (P12.Length != 0) hash ^= P12.GetHashCode();
    if (P13.Length != 0) hash ^= P13.GetHashCode();
    if (P14.Length != 0) hash ^= P14.GetHashCode();
    if (P15.Length != 0) hash ^= P15.GetHashCode();
    if (P16.Length != 0) hash ^= P16.GetHashCode();
    if (P17.Length != 0) hash ^= P17.GetHashCode();
    if (P18.Length != 0) hash ^= P18.GetHashCode();
    if (P19.Length != 0) hash ^= P19.GetHashCode();
    if (P20.Length != 0) hash ^= P20.GetHashCode();
    if (P21.Length != 0) hash ^= P21.GetHashCode();
    if (P22.Length != 0) hash ^= P22.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (P1.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(P1);
    }
    if (P2.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(P2);
    }
    if (P3.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(P3);
    }
    if (P4.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(P4);
    }
    if (P5.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(P5);
    }
    if (P6.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(P6);
    }
    if (P7.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(P7);
    }
    if (P8.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(P8);
    }
    if (P9.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(P9);
    }
    if (P10.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(P10);
    }
    if (P11.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(P11);
    }
    if (P12.Length != 0) {
      output.WriteRawTag(98);
      output.WriteString(P12);
    }
    if (P13.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(P13);
    }
    if (P14.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(P14);
    }
    if (P15.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(P15);
    }
    if (P16.Length != 0) {
      output.WriteRawTag(130, 1);
      output.WriteString(P16);
    }
    if (P17.Length != 0) {
      output.WriteRawTag(138, 1);
      output.WriteString(P17);
    }
    if (P18.Length != 0) {
      output.WriteRawTag(146, 1);
      output.WriteString(P18);
    }
    if (P19.Length != 0) {
      output.WriteRawTag(154, 1);
      output.WriteString(P19);
    }
    if (P20.Length != 0) {
      output.WriteRawTag(162, 1);
      output.WriteString(P20);
    }
    if (P21.Length != 0) {
      output.WriteRawTag(170, 1);
      output.WriteString(P21);
    }
    if (P22.Length != 0) {
      output.WriteRawTag(178, 1);
      output.WriteString(P22);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (P1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P1);
    }
    if (P2.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P2);
    }
    if (P3.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P3);
    }
    if (P4.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P4);
    }
    if (P5.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P5);
    }
    if (P6.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P6);
    }
    if (P7.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P7);
    }
    if (P8.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P8);
    }
    if (P9.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P9);
    }
    if (P10.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P10);
    }
    if (P11.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P11);
    }
    if (P12.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P12);
    }
    if (P13.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P13);
    }
    if (P14.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P14);
    }
    if (P15.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(P15);
    }
    if (P16.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(P16);
    }
    if (P17.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(P17);
    }
    if (P18.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(P18);
    }
    if (P19.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(P19);
    }
    if (P20.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(P20);
    }
    if (P21.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(P21);
    }
    if (P22.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(P22);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SocketResponse other) {
    if (other == null) {
      return;
    }
    if (other.P1.Length != 0) {
      P1 = other.P1;
    }
    if (other.P2.Length != 0) {
      P2 = other.P2;
    }
    if (other.P3.Length != 0) {
      P3 = other.P3;
    }
    if (other.P4.Length != 0) {
      P4 = other.P4;
    }
    if (other.P5.Length != 0) {
      P5 = other.P5;
    }
    if (other.P6.Length != 0) {
      P6 = other.P6;
    }
    if (other.P7.Length != 0) {
      P7 = other.P7;
    }
    if (other.P8.Length != 0) {
      P8 = other.P8;
    }
    if (other.P9.Length != 0) {
      P9 = other.P9;
    }
    if (other.P10.Length != 0) {
      P10 = other.P10;
    }
    if (other.P11.Length != 0) {
      P11 = other.P11;
    }
    if (other.P12.Length != 0) {
      P12 = other.P12;
    }
    if (other.P13.Length != 0) {
      P13 = other.P13;
    }
    if (other.P14.Length != 0) {
      P14 = other.P14;
    }
    if (other.P15.Length != 0) {
      P15 = other.P15;
    }
    if (other.P16.Length != 0) {
      P16 = other.P16;
    }
    if (other.P17.Length != 0) {
      P17 = other.P17;
    }
    if (other.P18.Length != 0) {
      P18 = other.P18;
    }
    if (other.P19.Length != 0) {
      P19 = other.P19;
    }
    if (other.P20.Length != 0) {
      P20 = other.P20;
    }
    if (other.P21.Length != 0) {
      P21 = other.P21;
    }
    if (other.P22.Length != 0) {
      P22 = other.P22;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          P1 = input.ReadString();
          break;
        }
        case 18: {
          P2 = input.ReadString();
          break;
        }
        case 26: {
          P3 = input.ReadString();
          break;
        }
        case 34: {
          P4 = input.ReadString();
          break;
        }
        case 42: {
          P5 = input.ReadString();
          break;
        }
        case 50: {
          P6 = input.ReadString();
          break;
        }
        case 58: {
          P7 = input.ReadString();
          break;
        }
        case 66: {
          P8 = input.ReadString();
          break;
        }
        case 74: {
          P9 = input.ReadString();
          break;
        }
        case 82: {
          P10 = input.ReadString();
          break;
        }
        case 90: {
          P11 = input.ReadString();
          break;
        }
        case 98: {
          P12 = input.ReadString();
          break;
        }
        case 106: {
          P13 = input.ReadString();
          break;
        }
        case 114: {
          P14 = input.ReadString();
          break;
        }
        case 122: {
          P15 = input.ReadString();
          break;
        }
        case 130: {
          P16 = input.ReadString();
          break;
        }
        case 138: {
          P17 = input.ReadString();
          break;
        }
        case 146: {
          P18 = input.ReadString();
          break;
        }
        case 154: {
          P19 = input.ReadString();
          break;
        }
        case 162: {
          P20 = input.ReadString();
          break;
        }
        case 170: {
          P21 = input.ReadString();
          break;
        }
        case 178: {
          P22 = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
